FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip python3-dev build-essential graphviz \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_gpu.txt .

RUN pip3 install --upgrade pip
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install torch-scatter torch-sparse torch-cluster torch-spline-conv -f https://data.pyg.org/whl/torch-2.1.0+cu118.html
RUN pip3 install torch-geometric
RUN pip3 install -r requirements_gpu.txt

COPY . .

CMD ["python3", "main.py"]
