FROM python:3.11-slim

WORKDIR /app

# os packages
RUN apt-get update && apt-get install -y \
    build-essential \
    graphviz \
    && rm -rf /var/lib/apt/lists/*

# requirements
COPY requirements_cpu.txt .

# dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        torch==2.4.1+cpu \
        torchvision==0.19.1+cpu \
        torchaudio==2.4.1+cpu \
        --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir \
        torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric \
        -f https://data.pyg.org/whl/torch-2.4.1+cpu.html && \
    pip install --no-cache-dir \
        google-cloud-storage google-cloud-aiplatform kfp && \
    pip install --no-cache-dir -r requirements_cpu.txt && \
    pip install gcsfs


COPY . .


ENTRYPOINT ["python"]
CMD ["pipeline_runner.py"]
