# config file for pipeline_script.py
# specify the parameters for model deployment
# ENDPOINT_NAME : 'klrealestate'
# deploy_model: TRUE

project: my-gitrunning-55025
location: us-central1
pipeline_root: gs://my-graphbert-bucket/graphbert
display_name: graphbert-pipeline-run
template_path: graphbert_pipeline.yaml
IMAGE_URI: "us-central1-docker.pkg.dev/my-gitrunning-55025/my-docker-repo/myapp:latest"
parameter_values:
  # config_path: gs://my-graphbert-bucket/Pipeline/pipeline_config.yaml
  workdir: gs://my-graphbert-bucket/graphbert


